# Generated by Django 4.2.3 on 2023-07-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id_admin', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_admin', models.CharField(max_length=50)),
                ('prenom_admin', models.CharField(max_length=100)),
                ('sexe_admin', models.CharField(max_length=1)),
                ('email_admin', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.CharField(max_length=20)),
                ('classe', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2')], max_length=20)),
                ('day', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(max_length=100)),
                ('classroom', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('groupe', models.CharField(choices=[('Groupe 1', 'Groupe 1'), ('Groupe 2', 'Groupe 2'), ('IM', 'IM'), ('IA', 'IA'), ('GL', 'GL'), ('SI', 'SI'), ('SEIOT', 'SEIOT')], max_length=100)),
                ('masse_horraire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_fil', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_fil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id_prof', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_prof', models.CharField(max_length=50)),
                ('prenom_prof', models.CharField(max_length=100)),
                ('sexe_prof', models.CharField(max_length=1)),
                ('contact_prof', models.IntegerField(null=True)),
                ('email_prof', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_sal', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nom_sal', models.CharField(max_length=20)),
                ('cap_sal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('code_ue', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_ue', models.CharField(max_length=100)),
                ('nombre_credit_ue', models.IntegerField()),
                ('type_semestre_ue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id_mat', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_mat', models.CharField(max_length=50)),
                ('horaire_mat', models.IntegerField()),
                ('code_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.ue')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule_etu', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_etu', models.CharField(max_length=50)),
                ('prenom_etu', models.CharField(max_length=100)),
                ('sexe_etu', models.CharField(max_length=1)),
                ('date_nais_etu', models.DateField()),
                ('age_etu', models.IntegerField()),
                ('contact', models.IntegerField(unique=True)),
                ('email_etu', models.EmailField(max_length=254, unique=True)),
                ('id_fil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.filiere')),
            ],
        ),
    ]
