# Generated by Django 4.2.3 on 2023-07-04 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0002_administration_course_filiere_professeur_salle_ue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.AddField(
            model_name='course',
            name='masse_horraire_utilisee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='masse_horraire_utilisee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='classe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.salle'),
        ),
        migrations.AlterField(
            model_name='course',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.filiere'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semaine',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.matiere'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.professeur'),
        ),
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
