# Generated by Django 4.2.3 on 2023-07-06 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0004_emploi_semestre_delete_course_emploi_semestre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emploi',
            name='week_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='bgColor',
            field=models.CharField(blank=True, default='#00FF00', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='id_filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administration.filiere'),
        ),
        migrations.AddField(
            model_name='salle',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ue',
            name='id_fil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Administration.filiere'),
        ),
    ]
