# Generated by Django 4.2.3 on 2023-07-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0005_emploi_created_at_emploi_week_num_matiere_bgcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='matiere_enseigne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Administration.matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='bgColor',
            field=models.CharField(blank=True, default='#6A5ACD', max_length=100, null=True),
        ),
    ]
