# Generated by Django 4.2.3 on 2023-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0006_professeur_matiere_enseigne_alter_matiere_bgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='bgColor',
            field=models.CharField(blank=True, default='#BA55D3', max_length=100, null=True),
        ),
    ]
