# Generated by Django 4.2.3 on 2023-07-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0007_alter_matiere_bgcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploi',
            name='semestre',
        ),
        migrations.AlterField(
            model_name='matiere',
            name='bgColor',
            field=models.CharField(blank=True, default='#32CD32', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='type_semestre_ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administration.semestre'),
        ),
    ]
