# Generated by Django 4.2.3 on 2023-07-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0008_remove_emploi_semestre_alter_matiere_bgcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='current_time_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='bgColor',
            field=models.CharField(blank=True, default='#6A5ACD', max_length=100, null=True),
        ),
    ]
