# Generated by Django 4.2.3 on 2023-07-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0009_emploi_current_time_used_alter_matiere_bgcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploi',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='bgColor',
            field=models.CharField(blank=True, default='#00CED1', max_length=100, null=True),
        ),
    ]
