# Generated by Django 4.2.3 on 2023-07-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administration', '0012_alter_etudiant_user_alter_matiere_bgcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='age_Etu',
        ),
        migrations.AddField(
            model_name='emploi',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Administration.semestre'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='bgColor',
            field=models.CharField(blank=True, default='#8A2BE2', max_length=100, null=True),
        ),
    ]
